name: hurricane
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy<1.20
  - tropycal
  - erddapy==1.2.1
  - jupyter
  - cartopy
  - matplotlib
  - shapely
  - pandas==1.5.3
  - pip
  - python


